Controllers/AboutController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortfolioMVC.Data;
using PortfolioMVC.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace PortfolioMVC.Controllers
{
    public class AboutController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public AboutController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: About
        [Authorize]
        public async Task<IActionResult> Index() => View(await _context.About.ToListAsync());

        // GET: About/Create
        [Authorize]
        public IActionResult Create() => View();

        // POST: About/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,ImageFile,ImageDescription,IsPublished")] About about)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Save image to wwwroot/images/uploads
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(about.ImageFile.FileName);
                    string extension = Path.GetExtension(about.ImageFile.FileName);
                    about.ImageName = fileName = fileName + DateTime.Now.ToString("yymmddss") + extension;
                    var path = Path.Combine($"{wwwRootPath}/images/uploads/about/", fileName);
                    
                    using(var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await about.ImageFile.CopyToAsync(fileStream);
                    }
                }
                catch
                {
                    ViewBag.ImageError = "Please upload image too, would ya? Mkay.";
                    return View();
                }

                _context.Add(about);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: About/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.About.FindAsync(id);
            if (about == null)
            {
                return NotFound();
            }
            return View(about);
        }

        // POST: About/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,ImageName,ImageDescription,IsPublished")] About about)
        {
            if (id != about.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(about);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AboutExists(about.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(about);
        }

        // GET: About/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await _context.About
                .FirstOrDefaultAsync(m => m.Id == id);
            if (about == null)
            {
                return NotFound();
            }

            return View(about);
        }

        // POST: About/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var about = await _context.About.FindAsync(id);

            // Delete image from wwwroot/images/uploads
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "images/uploads/about", about.ImageName);
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            _context.About.Remove(about);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AboutExists(int id) => _context.About.Any(e => e.Id == id);
    }
}

Controllers/CourseController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortfolioMVC.Data;
using PortfolioMVC.Models;

namespace PortfolioMVC.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CourseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Course
        [Authorize]
        public async Task<IActionResult> Index() => View(await _context.Courses.ToListAsync());

        // GET: Course/Create
        [Authorize]
        public IActionResult Create() =>  View();

        // POST: Course/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseName,Institution,DateStart,DateEnd,Description")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Course/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Course/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CourseName,Institution,DateStart,DateEnd,Description")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Course/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Course/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id) => _context.Courses.Any(e => e.Id == id);
    }
}

Controllers/SkillController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortfolioMVC.Data;
using PortfolioMVC.Models;

namespace PortfolioMVC.Controllers
{
    public class SkillController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SkillController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Skill
        [Authorize]        
        public async Task<IActionResult> Index() => View(await _context.Skills.ToListAsync());

        // GET: Skill/Create
        [Authorize]
        public IActionResult Create() => View();

        // POST: Skill/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,SkillName,Icon")] Skill skill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(skill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(skill);
        }

        // GET: Skill/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skill = await _context.Skills.FindAsync(id);
            if (skill == null)
            {
                return NotFound();
            }
            return View(skill);
        }

        // POST: Skill/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SkillName,Icon")] Skill skill)
        {
            if (id != skill.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(skill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkillExists(skill.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(skill);
        }

        // GET: Skill/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skill = await _context.Skills
                .FirstOrDefaultAsync(m => m.Id == id);
            if (skill == null)
            {
                return NotFound();
            }

            return View(skill);
        }

        // POST: Skill/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var skill = await _context.Skills.FindAsync(id);
            _context.Skills.Remove(skill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SkillExists(int id) => _context.Skills.Any(e => e.Id == id);
    }
}

Controllers/WorkController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PortfolioMVC.Data;
using PortfolioMVC.Models;

namespace PortfolioMVC.Controllers
{
    public class WorkController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Work
        [Authorize]
        public async Task<IActionResult> Index() => View(await _context.Work.ToListAsync());

        // GET: Work/Create
        [Authorize]
        public IActionResult Create() => View();

        // POST: Work/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Company,Title,DateStart,DateEnd,Description")] Work work)
        {
            if (ModelState.IsValid)
            {
                _context.Add(work);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(work);
        }

        // GET: Work/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work.FindAsync(id);
            if (work == null)
            {
                return NotFound();
            }
            return View(work);
        }

        // POST: Work/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Company,Title,DateStart,DateEnd,Description")] Work work)
        {
            if (id != work.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(work);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkExists(work.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(work);
        }

        // GET: Work/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.Work
                .FirstOrDefaultAsync(m => m.Id == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        // POST: Work/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var work = await _context.Work.FindAsync(id);
            _context.Work.Remove(work);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkExists(int id) => _context.Work.Any(e => e.Id == id);
    }
}

Views/Shared/_AdminScripts.cshtml
<script>
    window.onload = () => {    
        $(document).scrollTop($("main").offset().top);
    }
</script>

Views/Shared/_Contact.cshtml
<section id="contact" class="section-padding">
    <h2>Get In Touch</h2>
    <div class="divider"></div>
    <div class="contact-icons">
        <a href="https://www.linkedin.com/in/jonathan-laasonen-974aa617a/"
            target="_blank" 
            class="icon-link" 
            aria-label="LinkedIn Link">
            <i class="fab fa-linkedin fa-2x"></i>
        </a> 
                
        <a href="https://github.com/jona-laa/" 
            target="_blank"
            class="icon-link" 
            aria-label="GitHub Link">
            <i class="fab fa-github fa-2x"></i>
        </a> 
            
        <a href="mailto:jona.laa.dev@gmail.com" 
            target="_blank" 
            class="icon-link"
            aria-label="Send Email Link">
            <i class="fas fa-envelope fa-2x"></i>
        </a>
    </div>
</section>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="icon" type="image/png" href="~/favicon.ico">
	<link rel="apple-touch-icon" href="~/images/AppleTouchIcon.png">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
		integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
		crossorigin="anonymous">
	<meta name="description" content="Jonathan's portfolio site">
	<meta property="og:image" content="~/images/me.jpg">
	<link rel="stylesheet" href="~/css/site.css">
	<title>Jonathan Laasonen | @ViewData["title"]</title>
</head>

<body id="home">
	<header class="hero">
		<div class="header-content">
			<nav class="main-menu">
				<!-- Mobile meny - Hidden on default --> 
                <a 
                    href="" 
                    onclick="event.preventDefault()"
					id="main-menu-toggle" 
                    aria-label="Toggle Mobile Menu">
                    <svg 
                        viewBox="0 0 100 80" 
                        width="40"
						height="40">
						<rect 
                            width="90" 
                            height="10" 
                            fill="#f7f7f7">
                        </rect>
						<rect 
                            y="30" 
                            width="90" 
                            height="10" 
                            fill="#f7f7f7">
                        </rect>
						<rect 
                            y="60" 
                            width="90" 
                            height="10" 
                            fill="#f7f7f7">
                        </rect>
					</svg>
                </a>

                <!-- Main Menu - Blog page has different menu -->
                @if(IsSectionDefined("blogMenu"))
                {
                    RenderSection("blogMenu");
                }
                else
                {
                    <partial name="_MenuPartial" />
                }
			</nav>

            <!-- Don't show social media links when logged in -->
            @if (!SignInManager.IsSignedIn(User))
            {
                <div class="social">
                    <a 
                        href="https://github.com/jona-laa/" 
                        target="_blank" 
                        class="icon-link"
                        aria-label="GitHub Link">
                        <i class="fab fa-github fa-2x"></i>
                    </a> 
                    <a
                        href="https://www.linkedin.com/in/jonathan-laasonen-974aa617a/" 
                        target="_blank" 
                        class="icon-link"
                        aria-label="LinkedIn Link">
                        <i class="fab fa-linkedin fa-2x"></i>
                    </a>
                </div>
            }

		</div>
        @if (SignInManager.IsSignedIn(User))
        {
            <!-- If signed in show page specific or default hero content -->
            @if(IsSectionDefined("heroContent"))
            {
                RenderSection("heroContent");
            }
            else{
                <div class="hero-content">
                    <h1 class="title">Welcome</h1>
                    <p class="tagline centered">Choose Category to Edit from Menu</p>
                </div>
            }
        }
        else 
        {
            <!-- Show blog or default hero content -->
            @if(IsSectionDefined("heroContent"))
            {
                @RenderSection("heroContent")
            }
            else
            {
                <div class="hero-content">
                    <h1 class="title">Jonathan Laasonen</h1>
                    <p class="tagline">Web Developer</p>
                    <a href="#about-me" 
                        class="arrow-link"
                        aria-label="Scroll to About Section">
                        <i class="fas fa-chevron-down fa-3x"></i>
                    </a>
                </div>   
            }
        }
	</header>
    <div class="container">
    	@RenderBody()
    </div>
	<footer class="bg-dark">
        <small>&copy; 2021 Jona.Laa.Dev </small>
        <!-- To Top Button --> 
        <a 
            href="#home" 
            id="goTop"
			class="btn-top" 
            aria-label="Go To Top"
        >
            <svg 
                class="arrow up" 
                xmlns="http://www.w3.org/2000/svg"
				xmlns:xlink="http://www.w3.org/1999/xlink" 
                viewBox="5 0 50 80" 
                xml:space="preserve">
				    <polyline 
                        fill="none" 
                        stroke="#FFFFFF" 
                        stroke-width="8" 
                        stroke-linecap="round" 
                        stroke-linejoin="round"
					    points="0.375, 35.375 28.375, 0.375 58.67, 35.375 "/>
			</svg>
        </a>
    </footer>

    <!-- Scripts -->
	<script src="~/js/jquery-3.1.1.min.js"></script>
	<script src="~/js/site.js"></script>
	<script src="~/js/utils.js"></script>
	<script src="~/js/nav.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
<ul id="menu-main-menu" class="menu">
    <li>
        <a 
            asp-controller="Home" 
            asp-action="Index"
            class="menu-link">
            Preview
        </a>
    </li>
    <li>
        <a 
            asp-controller="About" 
            asp-action="Index"
            class="menu-link">
            About
        </a>
    </li>
    <li>
        <a 
            asp-controller="Skill" 
            asp-action="Index"
            class="menu-link">
            Skills
        </a>
    </li>
    <li>
        <a 
            asp-controller="Work" 
            asp-action="Index"
            class="menu-link">
            Work
        </a>
    </li>
    <li>
        <a 
            asp-controller="Course" 
            asp-action="Index"
            class="menu-link">
            Course
        </a>
    </li>
    <li>
        <a 
            asp-controller="Project" 
            asp-action="Index"
            class="menu-link">
            Portfolio
        </a>
    </li>
    <li>
        <a 
            asp-controller="Blog" 
            asp-action="Admin"
            class="menu-link">
            Blog
        </a>
    </li>

    <li>
        <a 
            class="menu-link" 
            asp-area="Identity" 
            asp-page="/Account/Manage/Index" 
            title="Manage">
            Profile
        </a>
    </li>
    <li>
        <a
            class="menu-link"
            id="logout-btn"
            asp-area="Identity"
            asp-page="/Account/Logout"
            asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })"
            >
                Logout
        </a>
    </li>
    </ul>
}
else
{
<ul id="menu-main-menu" class="menu">
    <li>
        <a 
            href="#about-me" 
            class="menu-link">
            About Me
        </a>
    </li>
    <li>
        <a 
            href="#skillset" 
            class="menu-link">
            Skillset
        </a>
    </li>
    <li>
        <a 
            href="#resume" 
            class="menu-link">
            Resume
        </a>
    </li>
    <li>
        <a 
            href="#portfolio" 
            class="menu-link">
            Portfolio
        </a>
    </li>
    <li>
        <a 
            asp-controller="Blog" 
            asp-action="Index"
            class="menu-link">
            Blog
        </a>
    </li>
</ul>
}

Views/Shared/_Pager.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<p class="pager">
@if (SignInManager.IsSignedIn(User))
{
    @if (ViewBag.HasPreviousPage)
    {
        <a class="prev" href="@Url.Action("Admin", "Blog" , new { page = ViewBag.PreviousPage })">
            <i class="fas fa-chevron-left" aria-label="Previous Page"></i>
        </a>
    }

    @if (ViewBag.HasNextPage)
    {
        <a class="next" href="@Url.Action("Admin", "Blog" , new { page = ViewBag.NextPage })">
            <i class="fas fa-chevron-right" aria-label="Next Page"></i>
        </a>
    }
}
else
{
    @if (ViewBag.HasPreviousPage)
    {
        <a class="prev" href="@Url.Action("Index", "Blog" , new { page = ViewBag.PreviousPage })">
            <i class="fas fa-chevron-left" aria-label="Previous Page"></i>
        </a>
    }

    @if (ViewBag.HasNextPage)
    {
        <a class="next" href="@Url.Action("Index", "Blog" , new { page = ViewBag.NextPage })">
            <i class="fas fa-chevron-right" aria-label="Next Page"></i>
        </a>
    }
}
</p>

Views/Shared/_Post.cshtml
@model PortfolioMVC.Models.BlogPost

<article class="about-container post">
    <div>
        <div>
            <figure class="post-figure">
                <img src="/images/uploads/blog/@(Model.ImageName)" alt="@Model.ImageAltText">
                <figcaption>@Model.ImageDescription</figcaption>
            </figure>
            <a href="@Url.Action("Post", "Blog", new { key = Model.Key })" class="post-heading-link">
                <h3 class="post-heading">@Model.Title</h3>
            </a>
            <div class="post-body">
                <p>@Html.Raw(Model.Body.Replace("\n", "</p><p>"))</p>
            </div>
            <div class="post-info">
                <span> @Model.Author | @Model.Posted.ToString("D")</span>
            </div>
        </div>
    <div class="divider"></div>
    </div>
</article>